// Package rules provides pre-built detection rules for blockchain security.
package rules

import (
	"time"

	"boundary-siem/internal/correlation"
)

// GetAllRules returns all pre-built detection rules.
func GetAllRules() []*correlation.Rule {
	var rules []*correlation.Rule

	rules = append(rules, GetValidatorRules()...)
	rules = append(rules, GetConsensusRules()...)
	rules = append(rules, GetTransactionRules()...)
	rules = append(rules, GetContractRules()...)
	rules = append(rules, GetMEVRules()...)
	rules = append(rules, GetInfrastructureRules()...)
	rules = append(rules, GetSecurityRules()...)
	rules = append(rules, GetComplianceRules()...)
	rules = append(rules, GetKeyManagementRules()...)
	rules = append(rules, GetCloudSecurityRules()...)
	rules = append(rules, GetNetworkRules()...)
	rules = append(rules, GetAPISecurityRules()...)
	rules = append(rules, GetDeFiRules()...)
	rules = append(rules, GetExchangeRules()...)

	// Cross-system ecosystem rules
	rules = append(rules, GetEcosystemRules()...)

	return rules
}

// GetDeFiRules returns DeFi-specific detection rules.
func GetDeFiRules() []*correlation.Rule {
	return []*correlation.Rule{
		{
			ID:          "defi-001",
			Name:        "Large Liquidity Removal",
			Description: "Large liquidity removal from DEX pool",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"defi", "liquidity", "removal"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "contract.liquidity.removed"},
				{Field: "metadata.value_usd", Operator: "gte", Value: float64(100000)},
			},
			GroupBy: []string{"metadata.pool"},
			Window:  15 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "defi-002",
			Name:        "Oracle Price Manipulation",
			Description: "Potential oracle price manipulation detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"defi", "oracle", "manipulation"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0040",
				TacticName:  "Impact",
				TechniqueID: "T1565",
			},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "oracle.price_deviation"},
				{Field: "metadata.deviation_percent", Operator: "gte", Value: float64(10)},
			},
			GroupBy: []string{"metadata.oracle"},
			Window:  5 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "defi-003",
			Name:        "Lending Protocol Liquidation Spike",
			Description: "Unusual number of liquidations in lending protocol",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"defi", "lending", "liquidation"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "contract.lending.liquidation"},
			},
			GroupBy: []string{"metadata.protocol"},
			Window:  30 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 10, Operator: "gte"},
		},
		{
			ID:          "defi-004",
			Name:        "Yield Farm Exit",
			Description: "Large withdrawal from yield farming protocol",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"defi", "yield", "farming"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "contract.vault.withdraw"},
				{Field: "metadata.value_usd", Operator: "gte", Value: float64(500000)},
			},
			GroupBy: []string{"metadata.vault"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "defi-005",
			Name:        "Stablecoin Depeg Event",
			Description: "Stablecoin price deviated from peg",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"defi", "stablecoin", "depeg"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0040",
				TacticName:  "Impact",
				TechniqueID: "T1565.001",
			},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "stablecoin.depeg"},
			},
			GroupBy: []string{"metadata.token"},
			Window:  15 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "defi-006",
			Name:        "Protocol Pause Event",
			Description: "DeFi protocol was paused",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"defi", "protocol", "pause"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "contract.paused"},
			},
			GroupBy: []string{"metadata.contract"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "defi-007",
			Name:        "Bridge Deposit Anomaly",
			Description: "Unusual bridge deposit activity",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"defi", "bridge", "deposit"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0010",
				TacticName:  "Exfiltration",
				TechniqueID: "T1537",
			},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "bridge.deposit"},
				{Field: "metadata.value_usd", Operator: "gte", Value: float64(1000000)},
			},
			GroupBy: []string{"metadata.bridge"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
	}
}

// GetExchangeRules returns exchange-related detection rules.
func GetExchangeRules() []*correlation.Rule {
	return []*correlation.Rule{
		{
			ID:          "exch-001",
			Name:        "Abnormal Withdrawal Volume",
			Description: "Abnormally high withdrawal volume detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"exchange", "withdrawal", "volume"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "exchange.withdrawal"},
			},
			GroupBy: []string{"metadata.exchange"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 100, Operator: "gte"},
		},
		{
			ID:          "exch-002",
			Name:        "Hot Wallet Low Balance",
			Description: "Exchange hot wallet balance critically low",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"exchange", "wallet", "balance"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "wallet.low_balance"},
				{Field: "metadata.wallet_type", Operator: "eq", Value: "hot"},
			},
			GroupBy: []string{"metadata.wallet"},
			Window:  15 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "exch-003",
			Name:        "Order Book Manipulation",
			Description: "Potential order book manipulation detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"exchange", "orderbook", "manipulation"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0040",
				TacticName:  "Impact",
				TechniqueID: "T1565",
			},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "exchange.spoofing"},
			},
			GroupBy: []string{"metadata.pair"},
			Window:  10 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "exch-004",
			Name:        "API Key Compromise",
			Description: "Exchange API key potentially compromised",
			Type:        correlation.RuleTypeAggregate,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"exchange", "api", "compromise"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0006",
				TacticName:  "Credential Access",
				TechniqueID: "T1528",
			},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "contains", Value: "exchange.api"},
			},
			GroupBy: []string{"metadata.api_key"},
			Window:  1 * time.Hour,
			Aggregate: &correlation.AggregateConfig{
				Function: "count_distinct",
				Field:    "actor.ip",
				Operator: "gte",
				Value:    5,
			},
		},
		{
			ID:          "exch-005",
			Name:        "Wash Trading Pattern",
			Description: "Potential wash trading pattern detected",
			Type:        correlation.RuleTypeSequence,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"exchange", "wash", "trading"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "exchange.trade"},
				{Field: "metadata.self_trade", Operator: "eq", Value: true},
			},
			GroupBy: []string{"metadata.trader"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 10, Operator: "gte"},
		},
		{
			ID:          "exch-006",
			Name:        "Cold Wallet Movement",
			Description: "Funds moved from cold wallet",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"exchange", "cold", "wallet"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "wallet.cold.transfer"},
			},
			GroupBy: []string{"metadata.wallet"},
			Window:  24 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
	}
}

// GetValidatorRules returns validator-related detection rules.
func GetValidatorRules() []*correlation.Rule {
	return []*correlation.Rule{
		{
			ID:          "val-001",
			Name:        "Validator Slashing Event",
			Description: "Validator was slashed for protocol violation",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"validator", "slashing", "critical"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0040",
				TacticName:  "Impact",
				TechniqueID: "T1485",
			},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "validator.slashing_detected"},
			},
			GroupBy: []string{"metadata.validator_index"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "val-002",
			Name:        "Double Voting Detected",
			Description: "Validator submitted conflicting votes for same slot",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"validator", "double-vote", "slashing"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "validator.double_vote"},
			},
			GroupBy: []string{"metadata.validator_index"},
			Window:  5 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "val-003",
			Name:        "Surround Vote Detected",
			Description: "Validator submitted surround vote (slashable offense)",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"validator", "surround-vote", "slashing"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "validator.surround_vote"},
			},
			GroupBy: []string{"metadata.validator_index"},
			Window:  5 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "val-004",
			Name:        "Multiple Missed Attestations",
			Description: "Validator missed multiple attestation duties",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"validator", "attestation", "missed"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "validator.attestation_missed"},
			},
			GroupBy: []string{"metadata.validator_index"},
			Window:  30 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 3, Operator: "gte"},
		},
		{
			ID:          "val-005",
			Name:        "Missed Block Proposal",
			Description: "Validator missed their block proposal duty",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"validator", "proposal", "missed"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "validator.proposal_missed"},
			},
			GroupBy: []string{"metadata.validator_index"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "val-006",
			Name:        "Validator Sync Committee Missed",
			Description: "Validator missed sync committee contribution",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"validator", "sync-committee", "missed"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "validator.sync_committee_missed"},
			},
			GroupBy: []string{"metadata.validator_index"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 3, Operator: "gte"},
		},
		{
			ID:          "val-007",
			Name:        "Validator Effectiveness Degraded",
			Description: "Validator effectiveness dropped below threshold",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"validator", "effectiveness", "performance"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "contains", Value: "validator.attestation_missed"},
			},
			GroupBy: []string{"metadata.validator_index"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 10, Operator: "gte"},
		},
		{
			ID:          "val-008",
			Name:        "Validator Exit Initiated",
			Description: "Validator voluntary exit was initiated",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"validator", "exit", "lifecycle"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "validator.exited"},
			},
			GroupBy: []string{"metadata.validator_index"},
			Window:  24 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "val-009",
			Name:        "Multiple Validators Offline",
			Description: "Multiple validators went offline simultaneously",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"validator", "offline", "outage"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "validator.attestation_missed"},
			},
			GroupBy: []string{"source.host"},
			Window:  10 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 5, Operator: "gte"},
		},
		{
			ID:          "val-010",
			Name:        "Validator Balance Decrease",
			Description: "Validator balance decreased unexpectedly",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"validator", "balance", "slashing"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "validator.balance_decreased"},
				{Field: "metadata.decrease_reason", Operator: "eq", Value: "slashing"},
			},
			GroupBy: []string{"metadata.validator_index"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
	}
}

// GetConsensusRules returns consensus-related detection rules.
func GetConsensusRules() []*correlation.Rule {
	return []*correlation.Rule{
		{
			ID:          "con-001",
			Name:        "Beacon Chain Sync Failed",
			Description: "Beacon node failed to sync with network",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"consensus", "sync", "failure"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "beacon.sync_failed"},
			},
			GroupBy: []string{"source.host"},
			Window:  10 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 3, Operator: "gte"},
		},
		{
			ID:          "con-002",
			Name:        "Finality Delay",
			Description: "Chain finality is delayed beyond normal threshold",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"consensus", "finality", "delay"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "beacon.finality_delayed"},
			},
			GroupBy: []string{"source.host"},
			Window:  15 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "con-003",
			Name:        "Fork Detected",
			Description: "Chain fork detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"consensus", "fork", "reorg"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "beacon.fork_detected"},
			},
			GroupBy: []string{"source.host"},
			Window:  5 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "con-004",
			Name:        "Deep Chain Reorg",
			Description: "Deep chain reorganization detected (>6 blocks)",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"consensus", "reorg", "deep"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "block.reorg"},
				{Field: "metadata.reorg_depth", Operator: "gte", Value: float64(6)},
			},
			GroupBy: []string{"source.host"},
			Window:  30 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "con-005",
			Name:        "Low Peer Count",
			Description: "Node has critically low peer count",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"consensus", "peers", "network"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "peer.low_count"},
			},
			GroupBy: []string{"source.host"},
			Window:  10 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 3, Operator: "gte"},
		},
		{
			ID:          "con-006",
			Name:        "Execution Client Disconnected",
			Description: "Execution client disconnected from consensus client",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"consensus", "execution", "disconnect"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "beacon.execution_disconnected"},
			},
			GroupBy: []string{"source.host"},
			Window:  5 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "con-007",
			Name:        "Block Production Failure",
			Description: "Node failed to produce block when selected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"consensus", "block", "production"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "block.production_failed"},
			},
			GroupBy: []string{"source.host"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "con-008",
			Name:        "Invalid Block Received",
			Description: "Node received invalid block from peer",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"consensus", "block", "invalid"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "block.invalid"},
			},
			GroupBy: []string{"source.host"},
			Window:  30 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 5, Operator: "gte"},
		},
	}
}

// GetTransactionRules returns transaction-related detection rules.
func GetTransactionRules() []*correlation.Rule {
	return []*correlation.Rule{
		{
			ID:          "tx-001",
			Name:        "Large ETH Transfer",
			Description: "Unusually large ETH transfer detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"transaction", "transfer", "whale"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "tx.transfer"},
				{Field: "metadata.value_eth", Operator: "gte", Value: float64(1000)},
			},
			GroupBy: []string{"metadata.from"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "tx-002",
			Name:        "High Gas Price Transaction",
			Description: "Transaction with abnormally high gas price",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityLow,
			Tags:        []string{"transaction", "gas", "priority"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "contains", Value: "tx."},
				{Field: "metadata.gas_price_gwei", Operator: "gte", Value: float64(500)},
			},
			GroupBy: []string{"metadata.from"},
			Window:  15 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "tx-003",
			Name:        "Rapid Transaction Burst",
			Description: "Many transactions from same address in short period",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"transaction", "burst", "suspicious"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "contains", Value: "tx."},
			},
			GroupBy: []string{"metadata.from"},
			Window:  5 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 50, Operator: "gte"},
		},
		{
			ID:          "tx-004",
			Name:        "Failed Transaction Spike",
			Description: "High rate of failed transactions",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"transaction", "failed", "errors"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "contains", Value: "tx."},
				{Field: "outcome", Operator: "eq", Value: "failure"},
			},
			GroupBy: []string{"metadata.from"},
			Window:  15 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 10, Operator: "gte"},
		},
		{
			ID:          "tx-005",
			Name:        "Contract Deployment",
			Description: "New smart contract deployed",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityLow,
			Tags:        []string{"transaction", "contract", "deployment"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "tx.contract_deploy"},
			},
			GroupBy: []string{"metadata.from"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "tx-006",
			Name:        "Self-Destruct Transaction",
			Description: "Contract self-destruct detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"transaction", "contract", "selfdestruct"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "tx.selfdestruct"},
			},
			GroupBy: []string{"metadata.contract"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "tx-007",
			Name:        "Nonce Gap Detected",
			Description: "Transaction nonce gap detected indicating potential issues",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityLow,
			Tags:        []string{"transaction", "nonce", "gap"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "tx.nonce_gap"},
			},
			GroupBy: []string{"metadata.from"},
			Window:  30 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "tx-008",
			Name:        "Cross-Chain Bridge Transaction",
			Description: "Transaction to known bridge contract",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityLow,
			Tags:        []string{"transaction", "bridge", "cross-chain"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "tx.bridge_deposit"},
			},
			GroupBy: []string{"metadata.from"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
	}
}

// GetContractRules returns smart contract detection rules.
func GetContractRules() []*correlation.Rule {
	return []*correlation.Rule{
		{
			ID:          "sc-001",
			Name:        "Ownership Transfer",
			Description: "Smart contract ownership was transferred",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"contract", "ownership", "transfer"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "contract.ownership.transferred"},
			},
			GroupBy: []string{"metadata.contract"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "sc-002",
			Name:        "Proxy Implementation Changed",
			Description: "Upgradeable proxy implementation was changed",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"contract", "proxy", "upgrade"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "contract.proxy.upgraded"},
			},
			GroupBy: []string{"metadata.contract"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "sc-003",
			Name:        "Large Token Transfer",
			Description: "Unusually large ERC20 token transfer",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"contract", "erc20", "transfer"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "contract.erc20.transfer"},
				{Field: "severity", Operator: "gte", Value: 6},
			},
			GroupBy: []string{"metadata.contract"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "sc-004",
			Name:        "NFT Bulk Transfer",
			Description: "Multiple NFTs transferred in short period",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"contract", "erc721", "bulk"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "contract.erc721.transfer"},
			},
			GroupBy: []string{"metadata.from"},
			Window:  10 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 20, Operator: "gte"},
		},
		{
			ID:          "sc-005",
			Name:        "Token Approval Revoked",
			Description: "Token approval was revoked",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityLow,
			Tags:        []string{"contract", "approval", "revoke"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "contract.erc20.approval"},
				{Field: "metadata.value", Operator: "eq", Value: "0"},
			},
			GroupBy: []string{"metadata.owner"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "sc-006",
			Name:        "Unlimited Token Approval",
			Description: "Unlimited token approval granted",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"contract", "approval", "unlimited"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "contract.erc20.approval"},
				{Field: "metadata.unlimited", Operator: "eq", Value: true},
			},
			GroupBy: []string{"metadata.owner"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "sc-007",
			Name:        "Governance Proposal Created",
			Description: "New governance proposal was created",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityLow,
			Tags:        []string{"contract", "governance", "proposal"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "contract.governance.proposal_created"},
			},
			GroupBy: []string{"metadata.contract"},
			Window:  24 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "sc-008",
			Name:        "Flash Loan Detected",
			Description: "Flash loan transaction detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"contract", "defi", "flashloan"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "tx.flash_loan"},
			},
			GroupBy: []string{"metadata.borrower"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "sc-009",
			Name:        "Timelock Bypass Attempt",
			Description: "Attempt to bypass governance timelock",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"contract", "governance", "timelock"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "contract.timelock.bypass"},
			},
			GroupBy: []string{"metadata.contract"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "sc-010",
			Name:        "Reentrancy Attack Pattern",
			Description: "Potential reentrancy attack pattern detected",
			Type:        correlation.RuleTypeSequence,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"contract", "attack", "reentrancy"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0040",
				TacticName:  "Impact",
				TechniqueID: "T1499",
			},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "contract.call.recursive"},
			},
			GroupBy: []string{"metadata.contract"},
			Window:  1 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 3, Operator: "gte"},
		},
	}
}

// GetMEVRules returns MEV-related detection rules.
func GetMEVRules() []*correlation.Rule {
	return []*correlation.Rule{
		{
			ID:          "mev-001",
			Name:        "Sandwich Attack",
			Description: "Sandwich attack detected in mempool",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"mev", "sandwich", "attack"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "tx.sandwich"},
			},
			GroupBy: []string{"metadata.attacker"},
			Window:  15 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "mev-002",
			Name:        "Frontrunning Detected",
			Description: "Transaction frontrunning detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"mev", "frontrun"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "tx.mev"},
				{Field: "metadata.mev_type", Operator: "eq", Value: "frontrun"},
			},
			GroupBy: []string{"metadata.from"},
			Window:  15 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "mev-003",
			Name:        "Backrunning Detected",
			Description: "Transaction backrunning detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityLow,
			Tags:        []string{"mev", "backrun"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "tx.mev"},
				{Field: "metadata.mev_type", Operator: "eq", Value: "backrun"},
			},
			GroupBy: []string{"metadata.from"},
			Window:  15 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "mev-004",
			Name:        "Arbitrage Transaction",
			Description: "Arbitrage transaction detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityLow,
			Tags:        []string{"mev", "arbitrage"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "tx.arbitrage"},
			},
			GroupBy: []string{"metadata.from"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "mev-005",
			Name:        "High MEV Profit",
			Description: "MEV transaction with high profit",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"mev", "profit", "whale"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "contains", Value: "tx."},
				{Field: "metadata.mev_profit_eth", Operator: "gte", Value: float64(10)},
			},
			GroupBy: []string{"metadata.from"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "mev-006",
			Name:        "JIT Liquidity Detected",
			Description: "Just-in-time liquidity provision detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityLow,
			Tags:        []string{"mev", "jit", "liquidity"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "tx.jit_liquidity"},
			},
			GroupBy: []string{"metadata.from"},
			Window:  15 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "mev-007",
			Name:        "Bundle Detected",
			Description: "Flashbots/MEV bundle detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityLow,
			Tags:        []string{"mev", "bundle", "flashbots"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "tx.bundle"},
			},
			GroupBy: []string{"metadata.builder"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "mev-008",
			Name:        "Liquidation Bot Activity",
			Description: "Liquidation bot transaction detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityLow,
			Tags:        []string{"mev", "liquidation", "defi"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "tx.liquidation"},
			},
			GroupBy: []string{"metadata.from"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 5, Operator: "gte"},
		},
	}
}

// GetInfrastructureRules returns infrastructure detection rules.
func GetInfrastructureRules() []*correlation.Rule {
	return []*correlation.Rule{
		{
			ID:          "infra-001",
			Name:        "High CPU Usage",
			Description: "Node CPU usage above critical threshold",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"infrastructure", "cpu", "performance"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "metric.cpu.usage"},
				{Field: "metadata.value", Operator: "gte", Value: float64(90)},
			},
			GroupBy: []string{"source.host"},
			Window:  5 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 3, Operator: "gte"},
		},
		{
			ID:          "infra-002",
			Name:        "Memory Exhaustion",
			Description: "Node memory usage critically high",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"infrastructure", "memory", "exhaustion"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "metric.memory.usage"},
				{Field: "metadata.value", Operator: "gte", Value: float64(95)},
			},
			GroupBy: []string{"source.host"},
			Window:  2 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 2, Operator: "gte"},
		},
		{
			ID:          "infra-003",
			Name:        "Disk Space Critical",
			Description: "Node disk space critically low",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"infrastructure", "disk", "storage"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "metric.disk.usage"},
				{Field: "metadata.value", Operator: "gte", Value: float64(95)},
			},
			GroupBy: []string{"source.host"},
			Window:  5 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "infra-004",
			Name:        "Network Errors Spike",
			Description: "High rate of network errors detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"infrastructure", "network", "errors"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "contains", Value: "metric.network.error"},
			},
			GroupBy: []string{"source.host"},
			Window:  5 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 100, Operator: "gte"},
		},
		{
			ID:          "infra-005",
			Name:        "Connection Flood",
			Description: "Abnormally high connection count (potential DDoS)",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"infrastructure", "ddos", "connections"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0040",
				TacticName:  "Impact",
				TechniqueID: "T1498",
			},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "metric.connection.count"},
				{Field: "metadata.value", Operator: "gte", Value: float64(10000)},
			},
			GroupBy: []string{"source.host"},
			Window:  1 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "infra-006",
			Name:        "Process Crash",
			Description: "Node process crashed unexpectedly",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"infrastructure", "crash", "process"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "process.crashed"},
			},
			GroupBy: []string{"source.host"},
			Window:  10 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "infra-007",
			Name:        "Database Latency High",
			Description: "Database query latency above threshold",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"infrastructure", "database", "latency"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "metric.latency.database"},
				{Field: "metadata.value_ms", Operator: "gte", Value: float64(1000)},
			},
			GroupBy: []string{"source.host"},
			Window:  5 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 10, Operator: "gte"},
		},
		{
			ID:          "infra-008",
			Name:        "SSL Certificate Expiring",
			Description: "SSL certificate expiring soon",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"infrastructure", "ssl", "certificate"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "cert.expiring"},
				{Field: "metadata.days_remaining", Operator: "lte", Value: float64(30)},
			},
			GroupBy: []string{"metadata.domain"},
			Window:  24 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
	}
}

// GetSecurityRules returns security detection rules.
func GetSecurityRules() []*correlation.Rule {
	return []*correlation.Rule{
		{
			ID:          "sec-001",
			Name:        "Blocked RPC Method Access",
			Description: "Attempt to call blocked/sensitive RPC method",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"security", "rpc", "blocked"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0001",
				TacticName:  "Initial Access",
				TechniqueID: "T1190",
			},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "contains", Value: "rpc.admin"},
			},
			GroupBy: []string{"actor.ip"},
			Window:  5 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "sec-002",
			Name:        "RPC Enumeration Attack",
			Description: "Source enumerating available RPC methods",
			Type:        correlation.RuleTypeAggregate,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"security", "rpc", "enumeration"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0007",
				TacticName:  "Discovery",
				TechniqueID: "T1046",
			},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "contains", Value: "rpc."},
			},
			GroupBy: []string{"actor.ip"},
			Window:  5 * time.Minute,
			Aggregate: &correlation.AggregateConfig{
				Function: "count_distinct",
				Field:    "target",
				Operator: "gte",
				Value:    20,
			},
		},
		{
			ID:          "sec-003",
			Name:        "Rate Limit Exceeded",
			Description: "Source exceeded API rate limits",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"security", "ratelimit", "abuse"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "contains", Value: "rpc."},
			},
			GroupBy: []string{"actor.ip"},
			Window:  1 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 100, Operator: "gte"},
		},
		{
			ID:          "sec-004",
			Name:        "Authentication Failure Spike",
			Description: "Multiple authentication failures from source",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"security", "auth", "brute-force"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0006",
				TacticName:  "Credential Access",
				TechniqueID: "T1110",
			},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "auth.failed"},
			},
			GroupBy: []string{"actor.ip"},
			Window:  10 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 10, Operator: "gte"},
		},
		{
			ID:          "sec-005",
			Name:        "Key Export Attempt",
			Description: "Attempt to export cryptographic key",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"security", "keys", "export"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0010",
				TacticName:  "Exfiltration",
				TechniqueID: "T1552",
			},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "key.export"},
			},
			GroupBy: []string{"target"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "sec-006",
			Name:        "Signing Anomaly",
			Description: "Unusual signing pattern detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"security", "signing", "anomaly"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "key.sign"},
			},
			GroupBy: []string{"target"},
			Window:  5 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 500, Operator: "gte"},
		},
		{
			ID:          "sec-007",
			Name:        "Privilege Escalation",
			Description: "Privilege escalation attempt detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"security", "privilege", "escalation"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0004",
				TacticName:  "Privilege Escalation",
				TechniqueID: "T1068",
			},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "auth.privilege_escalation"},
			},
			GroupBy: []string{"actor.id"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "sec-008",
			Name:        "Suspicious Process Execution",
			Description: "Suspicious process execution detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"security", "process", "suspicious"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0002",
				TacticName:  "Execution",
				TechniqueID: "T1059",
			},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "process.suspicious"},
			},
			GroupBy: []string{"source.host"},
			Window:  15 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "sec-009",
			Name:        "SSH Brute Force",
			Description: "SSH brute force attack detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"security", "ssh", "brute-force"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0006",
				TacticName:  "Credential Access",
				TechniqueID: "T1110.001",
			},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "ssh.failed"},
			},
			GroupBy: []string{"actor.ip"},
			Window:  5 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 20, Operator: "gte"},
		},
		{
			ID:          "sec-010",
			Name:        "Firewall Rule Change",
			Description: "Firewall rules were modified",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"security", "firewall", "change"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "firewall.rule_changed"},
			},
			GroupBy: []string{"actor.id"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
	}
}

// GetComplianceRules returns compliance detection rules.
func GetComplianceRules() []*correlation.Rule {
	return []*correlation.Rule{
		{
			ID:          "comp-001",
			Name:        "OFAC Sanctioned Address",
			Description: "Transaction involving OFAC sanctioned address",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"compliance", "ofac", "sanctions"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "threat.screening"},
				{Field: "outcome", Operator: "eq", Value: "failure"},
				{Field: "metadata.risk_level", Operator: "eq", Value: "critical"},
			},
			GroupBy: []string{"target"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "comp-002",
			Name:        "Mixer Interaction",
			Description: "Transaction involving known mixer service",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"compliance", "mixer", "aml"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "threat.screening"},
				{Field: "metadata.threat_types", Operator: "contains", Value: "mixer"},
			},
			GroupBy: []string{"target"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "comp-003",
			Name:        "Large Value Transaction",
			Description: "Transaction above reporting threshold",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"compliance", "reporting", "threshold"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "contains", Value: "tx."},
				{Field: "metadata.value_usd", Operator: "gte", Value: float64(10000)},
			},
			GroupBy: []string{"metadata.from"},
			Window:  24 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "comp-004",
			Name:        "Structuring Pattern",
			Description: "Possible structuring pattern detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"compliance", "structuring", "suspicious"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "contains", Value: "tx."},
				{Field: "metadata.value_usd", Operator: "gte", Value: float64(8000)},
				{Field: "metadata.value_usd", Operator: "lt", Value: float64(10000)},
			},
			GroupBy: []string{"metadata.from"},
			Window:  24 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 3, Operator: "gte"},
		},
		{
			ID:          "comp-005",
			Name:        "High-Risk Jurisdiction",
			Description: "Transaction involving high-risk jurisdiction",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"compliance", "jurisdiction", "fatf"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "threat.screening"},
				{Field: "metadata.high_risk_jurisdiction", Operator: "eq", Value: true},
			},
			GroupBy: []string{"target"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "comp-006",
			Name:        "Ransomware Address",
			Description: "Transaction involving known ransomware address",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"compliance", "ransomware", "cybercrime"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "threat.screening"},
				{Field: "metadata.threat_types", Operator: "contains", Value: "ransomware"},
			},
			GroupBy: []string{"target"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
	}
}

// GetKeyManagementRules returns key management detection rules.
func GetKeyManagementRules() []*correlation.Rule {
	return []*correlation.Rule{
		{
			ID:          "key-001",
			Name:        "Key Export Attempt",
			Description: "Cryptographic key export was attempted",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"keys", "export", "critical"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "key.export"},
			},
			GroupBy: []string{"target"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "key-002",
			Name:        "Key Import",
			Description: "Cryptographic key was imported",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"keys", "import"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "key.import"},
			},
			GroupBy: []string{"target"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "key-003",
			Name:        "Key Rotation",
			Description: "Cryptographic key was rotated",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"keys", "rotation"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "key.rotate"},
			},
			GroupBy: []string{"target"},
			Window:  24 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "key-004",
			Name:        "Key Revocation",
			Description: "Cryptographic key was revoked",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"keys", "revocation"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "key.revoke"},
			},
			GroupBy: []string{"target"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "key-005",
			Name:        "Multiple Key Failures",
			Description: "Multiple key operation failures",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"keys", "failures"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "contains", Value: "key."},
				{Field: "outcome", Operator: "eq", Value: "failure"},
			},
			GroupBy: []string{"actor.id"},
			Window:  10 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 5, Operator: "gte"},
		},
		{
			ID:          "key-006",
			Name:        "Validator Key Access",
			Description: "Access to validator signing key",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"keys", "validator"},
			Conditions: []correlation.Condition{
				{Field: "metadata.key_type", Operator: "eq", Value: "validator"},
				{Field: "action", Operator: "in", Values: []string{"key.access", "key.sign"}},
			},
			GroupBy: []string{"target", "actor.id"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "key-007",
			Name:        "Withdrawal Key Access",
			Description: "Access to withdrawal key",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"keys", "withdrawal"},
			Conditions: []correlation.Condition{
				{Field: "metadata.key_type", Operator: "eq", Value: "withdrawal"},
			},
			GroupBy: []string{"target"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "key-008",
			Name:        "Unusual Key Actor",
			Description: "Key accessed by unusual actor",
			Type:        correlation.RuleTypeAggregate,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"keys", "unauthorized"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "contains", Value: "key."},
			},
			GroupBy: []string{"target"},
			Window:  1 * time.Hour,
			Aggregate: &correlation.AggregateConfig{
				Function: "count_distinct",
				Field:    "actor.id",
				Operator: "gte",
				Value:    3,
			},
		},
	}
}

// GetCloudSecurityRules returns cloud security detection rules.
func GetCloudSecurityRules() []*correlation.Rule {
	return []*correlation.Rule{
		{
			ID:          "cloud-001",
			Name:        "IAM Policy Changed",
			Description: "IAM policy was modified",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"cloud", "iam", "policy"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "in", Values: []string{
					"policy.attach", "policy.detach", "gcp.setiampolicy",
				}},
			},
			GroupBy: []string{"metadata.account_id"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "cloud-002",
			Name:        "Unauthorized Access Attempt",
			Description: "Unauthorized access to cloud resource",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"cloud", "access", "unauthorized"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0001",
				TacticName:  "Initial Access",
				TechniqueID: "T1078",
			},
			Conditions: []correlation.Condition{
				{Field: "outcome", Operator: "eq", Value: "failure"},
				{Field: "metadata.error_code", Operator: "contains", Value: "Unauthorized"},
			},
			GroupBy: []string{"actor.id"},
			Window:  10 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 5, Operator: "gte"},
		},
		{
			ID:          "cloud-003",
			Name:        "Resource Deletion",
			Description: "Cloud resource was deleted",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"cloud", "deletion", "critical"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "resource.delete"},
				{Field: "outcome", Operator: "eq", Value: "success"},
			},
			GroupBy: []string{"metadata.account_id"},
			Window:  15 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "cloud-004",
			Name:        "Logging Disabled",
			Description: "Cloud audit logging was disabled",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"cloud", "logging", "evasion"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0005",
				TacticName:  "Defense Evasion",
				TechniqueID: "T1562.008",
			},
			Conditions: []correlation.Condition{
				{Field: "metadata.event_name", Operator: "in", Values: []string{
					"StopLogging", "DeleteTrail", "UpdateTrail",
				}},
			},
			GroupBy: []string{"metadata.account_id"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "cloud-005",
			Name:        "Security Group Changed",
			Description: "Security group rules were modified",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"cloud", "security-group", "network"},
			Conditions: []correlation.Condition{
				{Field: "metadata.event_name", Operator: "in", Values: []string{
					"AuthorizeSecurityGroupIngress", "AuthorizeSecurityGroupEgress",
					"RevokeSecurityGroupIngress", "RevokeSecurityGroupEgress",
				}},
			},
			GroupBy: []string{"metadata.account_id"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "cloud-006",
			Name:        "New Region Activity",
			Description: "Activity in previously unused region",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"cloud", "region", "anomaly"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "contains", Value: "cloud."},
				{Field: "metadata.new_region", Operator: "eq", Value: true},
			},
			GroupBy: []string{"metadata.account_id", "metadata.region"},
			Window:  24 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
	}
}

// GetNetworkRules returns network detection rules.
func GetNetworkRules() []*correlation.Rule {
	return []*correlation.Rule{
		{
			ID:          "net-001",
			Name:        "Port Scan Detected",
			Description: "Port scanning activity detected",
			Type:        correlation.RuleTypeAggregate,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"network", "scan", "reconnaissance"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0007",
				TacticName:  "Discovery",
				TechniqueID: "T1046",
			},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "network.connection_refused"},
			},
			GroupBy: []string{"actor.ip"},
			Window:  5 * time.Minute,
			Aggregate: &correlation.AggregateConfig{
				Function: "count_distinct",
				Field:    "metadata.port",
				Operator: "gte",
				Value:    10,
			},
		},
		{
			ID:          "net-002",
			Name:        "Outbound to Malicious IP",
			Description: "Outbound connection to known malicious IP",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityCritical,
			Tags:        []string{"network", "malicious", "c2"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0011",
				TacticName:  "Command and Control",
				TechniqueID: "T1071",
			},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "network.outbound"},
				{Field: "metadata.threat_intel_match", Operator: "eq", Value: true},
			},
			GroupBy: []string{"source.host"},
			Window:  15 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "net-003",
			Name:        "DNS Tunnel Suspected",
			Description: "Possible DNS tunneling detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"network", "dns", "tunnel"},
			MITRE: &correlation.MITREMapping{
				TacticID:    "TA0011",
				TacticName:  "Command and Control",
				TechniqueID: "T1071.004",
			},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "dns.query"},
				{Field: "metadata.query_length", Operator: "gte", Value: float64(100)},
			},
			GroupBy: []string{"source.host"},
			Window:  15 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 10, Operator: "gte"},
		},
		{
			ID:          "net-004",
			Name:        "Unusual P2P Traffic",
			Description: "Unusual P2P network traffic pattern",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"network", "p2p", "anomaly"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "network.p2p"},
				{Field: "metadata.peers_connected", Operator: "gte", Value: float64(200)},
			},
			GroupBy: []string{"source.host"},
			Window:  30 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
	}
}

// GetAPISecurityRules returns API security detection rules.
func GetAPISecurityRules() []*correlation.Rule {
	return []*correlation.Rule{
		{
			ID:          "api-001",
			Name:        "API Key Abuse",
			Description: "API key used from multiple locations",
			Type:        correlation.RuleTypeAggregate,
			Enabled:     true,
			Severity:    correlation.SeverityHigh,
			Tags:        []string{"api", "key", "abuse"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "contains", Value: "api."},
				{Field: "metadata.api_key", Operator: "exists", Value: true},
			},
			GroupBy: []string{"metadata.api_key"},
			Window:  1 * time.Hour,
			Aggregate: &correlation.AggregateConfig{
				Function: "count_distinct",
				Field:    "actor.ip",
				Operator: "gte",
				Value:    5,
			},
		},
		{
			ID:          "api-002",
			Name:        "GraphQL Introspection",
			Description: "GraphQL introspection query detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityLow,
			Tags:        []string{"api", "graphql", "introspection"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "api.graphql.introspection"},
			},
			GroupBy: []string{"actor.ip"},
			Window:  1 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 1, Operator: "gte"},
		},
		{
			ID:          "api-003",
			Name:        "WebSocket Flood",
			Description: "WebSocket message flood detected",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityMedium,
			Tags:        []string{"api", "websocket", "flood"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "api.websocket.message"},
			},
			GroupBy: []string{"actor.ip"},
			Window:  1 * time.Minute,
			Threshold: &correlation.ThresholdConfig{Count: 1000, Operator: "gte"},
		},
		{
			ID:          "api-004",
			Name:        "Deprecated API Usage",
			Description: "Deprecated API endpoint accessed",
			Type:        correlation.RuleTypeThreshold,
			Enabled:     true,
			Severity:    correlation.SeverityLow,
			Tags:        []string{"api", "deprecated"},
			Conditions: []correlation.Condition{
				{Field: "action", Operator: "eq", Value: "api.deprecated"},
			},
			GroupBy: []string{"metadata.endpoint"},
			Window:  24 * time.Hour,
			Threshold: &correlation.ThresholdConfig{Count: 10, Operator: "gte"},
		},
	}
}
